local_mysql:
  db_type: mysql
  host: 127.0.0.1
  port: 3306
  user: qinzerui
  password: Qz.ZXJ.1997

remote_mysql:
  db_type: mysql
  host: rm-uf63lgd848335z49xyo.mysql.rds.aliyuncs.com
  port: 3306
  user: qinzerui
  password: Qz.ZXJ.1997