# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_pipe.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='data_pipe.proto',
    package='datapipe',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0f\x64\x61ta_pipe.proto\x12\x08\x64\x61tapipe\"-\n\x0fTransmitRequest\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1f\n\rTransmitReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32P\n\x08\x44\x61taFlow\x12\x44\n\x0cTransmitData\x12\x19.datapipe.TransmitRequest\x1a\x17.datapipe.TransmitReply\"\x00\x62\x06proto3')
)

_TRANSMITREQUEST = _descriptor.Descriptor(
    name='TransmitRequest',
    full_name='datapipe.TransmitRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='index', full_name='datapipe.TransmitRequest.index', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='msg', full_name='datapipe.TransmitRequest.msg', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=29,
    serialized_end=74,
)

_TRANSMITREPLY = _descriptor.Descriptor(
    name='TransmitReply',
    full_name='datapipe.TransmitReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='status', full_name='datapipe.TransmitReply.status', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=76,
    serialized_end=107,
)

DESCRIPTOR.message_types_by_name['TransmitRequest'] = _TRANSMITREQUEST
DESCRIPTOR.message_types_by_name['TransmitReply'] = _TRANSMITREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransmitRequest = _reflection.GeneratedProtocolMessageType('TransmitRequest', (_message.Message,), dict(
    DESCRIPTOR=_TRANSMITREQUEST,
    __module__='data_pipe_pb2'
    # @@protoc_insertion_point(class_scope:datapipe.TransmitRequest)
))
_sym_db.RegisterMessage(TransmitRequest)

TransmitReply = _reflection.GeneratedProtocolMessageType('TransmitReply', (_message.Message,), dict(
    DESCRIPTOR=_TRANSMITREPLY,
    __module__='data_pipe_pb2'
    # @@protoc_insertion_point(class_scope:datapipe.TransmitReply)
))
_sym_db.RegisterMessage(TransmitReply)

_DATAFLOW = _descriptor.ServiceDescriptor(
    name='DataFlow',
    full_name='datapipe.DataFlow',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=109,
    serialized_end=189,
    methods=[
        _descriptor.MethodDescriptor(
            name='TransmitData',
            full_name='datapipe.DataFlow.TransmitData',
            index=0,
            containing_service=None,
            input_type=_TRANSMITREQUEST,
            output_type=_TRANSMITREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_DATAFLOW)

DESCRIPTOR.services_by_name['DataFlow'] = _DATAFLOW

# @@protoc_insertion_point(module_scope)
